### ISSUE TITLE
DiscordAPIError[50006]: Cannot send an empty message

### ISSUE THREAD

**Issue by phoenix5980** [azusemst/discord-bilibili-embed#2]
/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/@discordjs/rest/dist/index.js:687
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[50006]: Cannot send an empty message
    at handleErrors (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/@discordjs/rest/dist/index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/@discordjs/rest/dist/index.js:1072:23)
    at async SequentialHandler.queueRequest (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/@discordjs/rest/dist/index.js:913:14)
    at async _REST.request (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async TextChannel.send (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)
    at async Timeout._onTimeout (/Users/phoenix/Downloads/GitHub/discord-bilibili-embed/events/ready.js:36:25) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: { message: 'Cannot send an empty message', code: 50006 },
  code: 50006,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1032564492292329482/messages'
}

**Comment by phoenix5980** [comment]
已自力解决。原因是需要认证Cookie：SESSDATA和csrf（bili_jct）
已提交Pull Request #3
